mode: "sumo_rl_events"

simulation:
  sumo_config: "Berlin/osm.sumocfg"
  simulation_speed: 0.1
  bounds:
    min_lat: 52.520
    max_lat: 52.531
    min_lon: 13.385
    max_lon: 13.405
  max_steps: 7200

model:
  hidden_layers: [64, 16]
  
fdrl:
  yellow_time: 3
  green_time: 30

system:
  controlled_junctions:
    - GS_21441737
    - GS_25954547
    - GS_26752062
    - GS_26753059
    - GS_659394041
    - cluster_262476527_26871569_311718989_3836987635_#3more
  model_save_path: ./FDRL/saved_models/global_model.pth

sumo_rl_events:
  model_path: "./FDRL/saved_models"
  # Model trained on 6 junctions: state_dim = 6*2 = 12, action_dim = 6
  state_dim: 8
  action_dim: 4
