sumo:
  config_file: sumo_files/mulund/osm.sumocfg
  step_length: 1.0
  gui: false
  gridlock_detection_time: 300.0
priority_weights:
  truck: 10.0
  bus: 5.0
  car: 1.0
  motorcycle: 1.0
fdrl:
  epochs: 50
  K: 500
  alpha: 0.05
  gamma: 0.99
  actor_lr: 0.0001
  critic_lr: 0.0005
  clip_epsilon: 0.2
  yellow_time: 3
  green_time: 10
model:
  hidden_layers:
  - 128
  - 64
  activation: relu
system:
  server_host: localhost
  server_port: 12345
  max_roads: 4
  controlled_junctions:
  - '1388354194'
  - cluster_10023271204_10023271205_6274819761_630699810
  - cluster_10260826682_1596008552
  - cluster_10275495182_1388354213
  - cluster_1386641179_5924611759_7285424910_7285424940
  - cluster_1388354178_5924612075
  - joinedS_5924612047_cluster_5924612046_619130306
  model_save_path: saved_models/universal_model.pth
  log_file: training_logs.json
  enable_patience: true
  patience_epochs: 20
  min_reward_delta: 0.05
